all:
	gcc -o merge-sort merge-sort.c utils.c -lm
	gcc -o merge-debug merge-debug.c utils.c -lm
	gcc -o merge-inplace merge-inplace.c utils.c -lm
	gcc -o merge-inv merge-inv.c utils.c -lm
	gcc -o merge-sum merge-sum.c utils.c -lm
	gcc -o merge-insert merge-insert.c utils.c -lm
	gcc -o merge-maximal merge-maximal.c utils.c -lm 
	gcc -o merge-tau merge-tau.c utils.c -lm
	gcc -o closest_pair closest_pair.c utils.c -lm
clean:
	rm merge-sort merge-debug merge-inplace merge-inv merge-sum merge-insert merge-maximal merge-tau closest_pair 
